### ISSUE TITLE
Faling to evaluate through locally hosted vLLM API

### ISSUE THREAD

**Issue by tongyx361** [Psycoy/MixEval#31]
The following command still evaluates on the local machine, instead of through API.

```shell
python -m mix_eval.evaluate \
    --model_name local_chat --model_path "meta-llama/Meta-Llama-3-8B-Instruct" \
    --api_base_url "http://${ip}:${port}/v1/chat/completions" \
    --benchmark mixeval_hard --version "2024-06-01" \
    --output_dir "mix_eval/data/model_responses/" \
    --batch_size 100 \
```

Is there anything wrong with my command or the code base?

**Comment by Psycoy** [comment]
Hi @tongyx361 ,

Are you wishing to run an api model or use an API model parser?
From your message I suppose you are trying to evaluate an api model, then you need to register a new model accordingly. Refer to [here](https://github.com/Psycoy/MixEval?tab=readme-ov-file#new-model-registration) for details.

Please note that `--api_base_url` is for model parser instead of the model evaluation.
